name:                math-logic-hw2
version:             0.1.0.0
github:              "smntin/math-logic-hw2"
license:             BSD3
author:              "SmnTin"
maintainer:          "smn.pankv@gmail.com"
copyright:           "2022 SmnTin"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/smntin/math-logic-hw2#readme>

dependencies:
- base >= 4.7 && < 5
- process
- temporary

library:
  source-dirs: src

executables:
  queens:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - math-logic-hw2

tests:
  math-logic-hw2-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - math-logic-hw2
    - tasty >= 1.4
    - tasty-hunit >= 0.10
    - tasty-quickcheck >= 0.10
    - tasty-smallcheck >= 0.8
